[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[phases.build]
cmds = [
    "python manage.py migrate --noinput || true"
]

[start]
cmd = "python -m gunicorn liftandlight.wsgi --bind 0.0.0.0:$PORT"

