services:
  - type: web
    name: liftandlight
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python -m gunicorn liftandlight.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: liftandlight.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.9
    database:
      name: liftandlight-db
      plan: free
      databaseName: liftandlight
      user: liftandlight

