services:
  - type: web
    name: liftandlight
    env: python
    buildCommand: python -m pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python -m gunicorn liftandlight.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: liftandlight.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@lifthlight.com
      - key: ADMIN_PASSWORD
        generateValue: true
    database:
      name: liftandlight-db
      plan: free
      databaseName: liftandlight
      user: liftandlight

